### ISSUE TITLE
Data translation

### ISSUE THREAD

**Issue by PierreAnctil** [worldskills/worldskills-infrastructure-list#10]
@worldskills/geeks 

As far as I know, the API and DB are ready for multilingual strings.

However I see many labels are `String` and not `I18nString` (`ItemSet` description as an example). Is there a reason behind it or is it a work in progress?

Regarding the UI I do not see any way to input several languages for a given label. How are translations supposed to be managed for data?

**Comment by gbervik** [comment]
If some fields are not an `I18nString` and you think they should be then feel free to refactor them. The example you give would make sense to be an `I18nString`

For the UI some of our other projects make use of `angular-translate`. For example, see https://github.com/worldskills/worldskills-organizations

**Comment by PierreAnctil** [comment]
Yes we are currently working with it to translate WSIL UI.
However that seem to be mainly aimed at translating static content and with some tweaks **display** translated data (but the API should already allow that without tweaks).
The real question is when an item (example) is created in a given language, where, when, by whom and how will the data be translated ?
A way to do it is to create a dedicated application allowing translators to manage translations for i18n tables from all databases. 

What do you think?

**Comment by gbervik** [comment]
I don't think a dedicated application for translating text is the way to go. The text should really be translated in context so that the translator has a full picture of what they are translating. I would prefer to have some type of language switcher on the form. So, for example, the user creates an item, then switches language and uses the same form to enter data for a new language. 

@fabian also has some examples from the Events application

**Comment by fabian** [comment]
Here are some examples how I implemented the translation of the Skill descriptions:

h3. Skill with English as base language

![screenshot 2017-12-22 15 51 57](https://user-images.githubusercontent.com/13346/34302209-472d1c6e-e730-11e7-8cff-ed4d0c6c274d.png)

h3. Translations overview

![screenshot 2017-12-22 15 52 03](https://user-images.githubusercontent.com/13346/34302227-544ef912-e730-11e7-97d4-77f4031c4a03.png)


h3. Language translation

![screenshot 2017-12-22 15 53 04](https://user-images.githubusercontent.com/13346/34302236-5c278244-e730-11e7-8b02-3aabe00ec653.png)


Also I don't think it makes sense to have _all_ text fields translatable. E.g. The Required Item description would always be in one language only to avoid communication problems, so no need to change that from `String` to `I18nString`.

**Comment by WorldSkillsFrance** [comment]
Hi all 
ok for Fabian solution

**Comment by PierreAnctil** [comment]
Permissions would also need to be translated

Display in IL:

![chrome_2018-01-31_15-46-58](https://user-images.githubusercontent.com/6544411/35629182-3f336198-069e-11e8-9c9d-975b8b8d1bad.png)

**Comment by PierreAnctil** [comment]
And also event names

**Comment by PierreAnctil** [comment]
and also categories

**Comment by PierreAnctil** [comment]
and Item status 
and quantity unit

NB: Quantity unit could be translated in the front since this seems a static list of values. But since Item status will become configurable for each event, it can only be translated in the DB.

**Comment by PierreAnctil** [comment]
To sum it up, in order to have IL fully translated, we now have to provide a translation UI for:

- item name
- item statuses
- item quantity units
- item category name
- item subcategory name
- event name
- category name
- permissions
- skill name (already implemented)

@worldskills/geeks how do you think we can do that without repeating the very same work each time?

( Having a dedicated application is still an option 😉 )

**Comment by gbervik** [comment]
The ideal would be to have a re-usable angular component that we could drop in whenever we have a translatable piece of text. So it would basically be a text field and a language picker.

**Comment by JonathanVanRaemdonck** [comment]
Just like @gbervik mentioned, the idea of an angular component seems to be the best option, both for devs and end users. 

With @PierreAnctil , we thought of an input component that could handle data translations where needed. We detailed an initial draft of what it could look like into [this Google Doc](https://docs.google.com/document/d/1fclY7bKUz0vSb42Rs37NQe-AJEzBBLly1nnAs46SSZM/edit?usp=sharing). 

Feel free to add comments directly on it if you have any question/suggestion.

**Comment by PierreAnctil** [comment]
So to sum it up a new angular component will be defined allowing to input several languages.

### Definition

The component will basically be an input with a language switch.

![image](https://user-images.githubusercontent.com/6544411/36107195-9e36d1be-1019-11e8-909c-fc39ca327d60.png)


The values on the switch are by default a list of all languages (or subset to be defined) or can be passed as a parameter (required languages).

### Validation
When languages are passed as a parameter and all languages are filled, a check will appear on the right of the component.

![image](https://user-images.githubusercontent.com/6544411/36107718-44fc1030-101b-11e8-8f25-2daac1ce9dc7.png)


The form should not be valid until all required languages are filled.

### Event data (item name, etc)

A list of required languages should be defined at the event level and passed to all i18n components in the event.

### Implementation

A directive would be the most handy for usage.

**Comment by gbervik** [comment]
Sounds good to me. The only thing I would add to that is that when we have a set of required languages we should also allow the addition of other languages. So if French and English are required, we should allow the addition of German and Russian if someone wants to add those too.

**Comment by PierreAnctil** [comment]
I was not sure about the "The form should not be valid until all required languages are filled." part. Maybe some contributors will be able to translate and then not be able to create items.

It might be more flexible to allow incomplete translations but to display them differently. Maybe a display component which will display the text differently when there are missing translations. This someone who is actually able to translate will be able to easily see the missing translations.

Or should we start simple and do that later?

**Comment by gbervik** [comment]
That's a good point. I like the flexible option.

**Comment by PierreAnctil** [comment]
**Immediate changes:**

→ item quantity units
translated in IL front

→ item statuses (events)
→ item name (IL)
→ item category name (IL)
→ item subcategory name (IL)
when a user edit a text then the user globally selected language is used as the update target

→ event names
in local language for now

→ categories
→ positions
translated in DB (translations to be sent to @fabian)

The translation component will have to be defined later

**Comment by PierreAnctil** [comment]
**Frensh Translations for categories :** 
General Installations → Installations générales
Workshop Installations →  Installations d'atelier
Materials / Consumables →  Matériaux / Consommables
Familiarisation materials →  Matériaux de familiarisation
Samples →  Échantillons

**Frensh Translations for positions :**
Workshop Sector Manager →  Référent de pôle
Workshop Manager →  Chef d'atelier
IL Manager →  Département technique

@WorldSkillsFrance Can you please confirm translations?

**Comment by WorldSkillsFrance** [comment]
@PierreAnctil  here below my remarques
# **French Translations for categories :**
General Installations → Installations générales
Workshop Installations → **Matériels**
Materials / Consumables → Matériaux / Consommables
Familiarisation materials → **Matériaux de familiarisation (can we mask @gbervik @fabian; if not @PierreAnctil replace by : "Plans"?)** 
Samples → Échantillons  - WSFR-Matériel Prépa Inter
# **French Translations for positions :**
Guest → Visiteurs **(@gbervik still can see in positions)**
Experts → Experts
Workshop Manager → Chef d'atelier
Skill Competition Manager → Superviseur Technique
Workshop Sector Manager → Référent de pôle
IL Manager → Région Organisatrice  « this is rôle « Organizer »  in the excel file »
WSFR IL Manager → Admin WSFR **(@gbervik still can see in positions)**

**Comment by PierreAnctil** [comment]
thanks @WorldSkillsFrance 

@fabian can you please add these translations in the IL database ?

**Comment by fabian** [comment]
@WorldSkillsFrance Okay, I've added the translations and the category "Familiarisation materials" is removed from all your lists now.

How important is the translation of the positions for you? Given we will look into cleaning some of the currently confusion around positions and permissions soon, should we wait with those translations to avoid further confusion?

**Comment by WorldSkillsFrance** [comment]
@fabian thx but in staging  or in production i still can see "Familiarisation materials"
![image](https://user-images.githubusercontent.com/33081412/36853314-6eb08162-1d6e-11e8-98b3-fc656ff2bcea.png)

I made a mistake for one of the category names. Could you change "Échantillons  - WSFR-Matériel Prépa Inter" by "WSFR-M2-Matériel Prépa Internationale" (sorry for that)

I also would like to now when someone will clic on "Who-is-who" ?

**Comment by fabian** [comment]
> @fabian thx but in staging or in production i still can see "Familiarisation materials"

Ah yes sorry, only tested the removal locally but forgot to execute it on staging and production. Done now.

> I made a mistake for one of the category names. Could you change "Échantillons - WSFR-Matériel Prépa Inter" by "WSFR-M2-Matériel Prépa Internationale" (sorry for that)

No problem. Done.

> I also would like to now when someone will clic on "Who-is-who" ?

Sorry, don't understand your question. Click on "Who-is-who" where exactly?

**Comment by WorldSkillsFrance** [comment]
```
> I also would like to now when someone will clic on "Who-is-who" ?

Sorry, don't understand your question. Click on "Who-is-who" where exactly?
```
In the oveview of a skills

**Comment by fabian** [comment]
Ah I see now. Probably best to remove that link actually.

**Comment by WorldSkillsFrance** [comment]
@gbervik 
**1-**Could you we have the same permission in "positions" & "Permissions?
**2-**Could you put all name in french ? 
Guest → Visiteurs 
Experts → Experts
Workshop Manager → Chef d'atelier
Skill Competition Manager → Superviseur Technique
Workshop Sector Manager → Référent de pôle
IL Manager → Région Organisatrice « this is rôle « Organizer » in the excel file »
WSFR IL Manager → Admin WSFR

**Comment by WorldSkillsFrance** [comment]
Yes I understood correctly following your explanations of the last time. I would just like to have the same "architecture/tree" for both (permission & position).
If I talk about that, it's because in the infrastructure lists on the overview tab we see the positions, that's why I want to have the same "architecture/tree" and traduction in french :)

**Comment by gbervik** [comment]
Hi @WorldSkillsFrance, we can translate that in to French. If you send me the text I'll add it.

**Comment by WorldSkillsFrance** [comment]
Hi Adam, please find below the french email template
[Trame Mail nouveau compte.docx](https://github.com/worldskills/worldskills-infrastructure-list/files/1796158/Trame.Mail.nouveau.compte.docx)

**Comment by WorldSkillsFrance** [comment]
Hi all,
Could someone delete the text as in the image if after?
Would it be possible to redirect to http://www.worldskills-france.org/ when you click on the WorldSkills logo?
![image](https://user-images.githubusercontent.com/33081412/37201219-55b00c54-2387-11e8-883d-8dc57c953da6.png)

**Comment by gbervik** [comment]
@WorldSkillsFrance thanks for the translation, but we can't make those emails specific to WorldSkills France. The logins that are created are used for both the WS France IL and all the WS International applications (and also any other Member that uses our software). 

The point is that the user just needs the one login to access applications for WS France, WS International, WS Europe or any other WorldSkills event that may use the software, so we will need to make that email text fairly generic.

**Comment by PierreAnctil** [comment]
@worldskills/geeks the item statuses are missing in staging DB 

Confirmed → Confirmé
Pending → En attente
Requested → Demandé
Secret → Secret

**Comment by WorldSkillsFrance** [comment]
**I would prefer :** 
Confirmed → Confirmé
Pending → En cours
Requested → A rechercher
Secret → Secret

**Comment by fabian** [comment]
Okay, I've added/updated the translations on staging. Will be deployed on production with the next deployment (probably next week).

**Comment by WorldSkillsFrance** [comment]
![image](https://user-images.githubusercontent.com/33081412/39037441-ce28daac-4480-11e8-9802-8d21259addf8.png)
it seemed to me that the language of the infrastructure lists was updated automatically according to the browser. Am I wrong ? (This picture has been made by one user in her first connection)

**Comment by WorldSkillsFrance** [comment]
Hi @PierreAnctil ,

When we are here (https://il.worldskills.org/#/event/438/overview) skills overview and when we change language,  skills does not change language the other menu yes but not skills. 
We need to refresh page. Could you have a look to fix that and make it works as everywhere else. 
Thank you

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance this is already referenced in https://github.com/worldskills/worldskills-infrastructure-list/issues/51

**Comment by WorldSkillsFrance** [comment]
@PierreAnctil i leave a message to Fabian in Issue 51.

Could you translate that (when we try to delet item in requeste item )
![image](https://user-images.githubusercontent.com/33081412/39431202-483f0aca-4c90-11e8-9c8c-217d39e322d2.png)

**Comment by WorldSkillsFrance** [comment]
@PierreAnctil 
Could you also translate this but and message : (when editing request item, and try to split it)
![image](https://user-images.githubusercontent.com/33081412/39432511-fa226482-4c93-11e8-85ca-203296d84e0e.png)

**Comment by WorldSkillsFrance** [comment]
Hi @PierreAnctil 

Could you fix the bug of skills name translation please.
![image](https://user-images.githubusercontent.com/33081412/40218388-4f62f4ee-5a71-11e8-9796-86f3268fa429.png)

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance what bug are you talking about? A missing translations? The translation must have been added on the skill meanwhile cause it seems to display correctly in production 

![image](https://user-images.githubusercontent.com/6544411/40343182-e913ccb0-5d8e-11e8-8163-89fd6ab5e52f.png)

**Comment by WorldSkillsFrance** [comment]
Yes im sure, it does not appear everytime but as you can see on the screenshot that i did we have something to do about it.

FYI @ailtisWSFR

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance do you remember in which case it can appear? Or is it completely random?

**Comment by WorldSkillsFrance** [comment]
@PierreAnctil I don't know maybe random.
Did you see my email about a meeting this afternoon ?
