### ISSUE TITLE
Customize logo

### ISSUE THREAD

**Issue by PierreAnctil** [worldskills/worldskills-infrastructure-list#11]
@WorldSkillsFrance has expressed the need do display the logo of worldskills france instead of the international logo.

![worldskills-france-small](https://user-images.githubusercontent.com/6544411/34263859-2d78053c-e671-11e7-94b8-401e617ed48d.jpg)

The current international logo is managed as base64 in the common CSS so that doesn't seem possible without changes.

Since it would have to be data-dependent, a logo will have to be defined at the Event or Organizer level.

Unless I'm missing something or something similar already does exists ?

Or is it an unwanted feature ?

**Comment by fabian** [comment]
No, we don't have any option to change the logo at the moment.

The logo used is actually not the WorldSkills International logo, but the logo of the WorldSkills movement, so it would apply to all Members of WorldSkills.

Adding a new logo field to the Event wouldn't solve the problem in all cases, as depending on the use case sometimes a different color version of the logo is needed.

I honestly would prefer to keep the same logo for all events for consistency within the application and with other applications.

The name of the event is displayed prominently at the top of the page, that should be enough to make it clear which event is being edited.

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance are you OK with that ?

**Comment by gbervik** [comment]
I spoke with David Hoey about this earlier today, and we are not going to allow the removal of the WorldSkills logo.

One option may be to have an additional logo like we allow with the CIS software.

**Comment by WorldSkillsFrance** [comment]
Hi everyone,
Ok Adam, sounds great, I'm happy with that option.

**Comment by fabian** [comment]
I personally don't think the additional work and complexity is worth having two WorldSkills logos in the header. There's currently a digital design review in progress and that might change how the header looks like - having two logos there could complicate things. But happy to discuss it during a Zoom session to better understand why a second WorldSkills logo is so important for you.

**Comment by WorldSkillsFrance** [comment]
ok no worries, we will discuss later this if it is necessary (it is not critical either). 
We are part of the "WorldSkills movement" to quoted Simon BARTLEY :) , and have no worries about having your logo on our IL.
Can you close the issue for the moment?
