### ISSUE TITLE
New IL manager

### ISSUE THREAD

**Issue by ailtisWSFR** [worldskills/worldskills-infrastructure-list#112]
@fabian 
Hi, 
We have a new colleague working at WorldSkills France for the Technical Department. 
I need to give him the IL admin permission for the IL. 
I've created a new profile on the People API for him (Jérémy ARSICAULT) and gave him the correct position and permission. 
When he connects himself to the list, Jérémy only get the public view permission (like an Expert). 
Am I missing something? Do I need to do another action to give him the IL admin permission? Or is there a bug somewhere? 

Screenshots of position and permission : 
![image](https://user-images.githubusercontent.com/39295271/42268891-ff47f442-7f7c-11e8-864e-df950509e047.png)
![image](https://user-images.githubusercontent.com/39295271/42268930-1571d170-7f7d-11e8-81a9-a10ef0f99c38.png)

Thanks

**Comment by fabian** [comment]
@ailtisWSFR I've discovered a bug in the IL system that prevented Jérémy from getting the correct access. I've fixed the bug and will deploy it to production on Monday. I will let you know once it is deployed.

**Comment by fabian** [comment]
@ailtisWSFR The fix has been deployed and Jérémy ARSICAULT can access the IL.

**Comment by ailtisWSFR** [comment]
@fabian Thanks, it's working now. We can close this issue if it's okay for you.
