### ISSUE TITLE
Show Extra details / Comments on Public View

### ISSUE THREAD

**Issue by fabian** [worldskills/worldskills-infrastructure-list#116]
@ailtisWSFR WorldSkills Kazan 2019 would like to show the field "Extra details / Comments" of Supplied Items on the public view. Is that okay for you or do you have some internal information that should not be made available in there?

**Comment by ailtisWSFR** [comment]
@fabian No problem for us. Actually, it is also something that would be good for us too, so we totally agree with WorldSkills Kazan 2019.

**Comment by fabian** [comment]
Added in https://github.com/worldskills/worldskills-infrastructure-list/commit/a2fbef6f67a30d2d4aaf8fd5b06283338e597e06.
