### ISSUE TITLE
Imposibility to delete a Requested Items

### ISSUE THREAD

**Issue by ailtisWSFR** [worldskills/worldskills-infrastructure-list#122]
Hi, 
I noticed today that on the "Skill View" the delete button doesn't work when you which to delete a Requested Item. (red cross)
When you click, you get the popup message "Are you sure, this will also remove any potential child-items?" but when I click on "OK", nothing is happening, even when I refresh the page. 

![image](https://user-images.githubusercontent.com/39295271/48185224-aa506480-e334-11e8-868c-503fe7f27b58.png)

Thanks in advance.

**Comment by fabian** [comment]
@ailtisWSFR Thanks for the report! I've pushed now a fix for this, can you confirm it works now?

**Comment by fabian** [comment]
Okay, just got another error report, looks like it's not totally fixed yet… 😉

**Comment by ailtisWSFR** [comment]
@fabian It does work now! Thanks a lot!
