### ISSUE TITLE
Recommendations appear multiple times

### ISSUE THREAD

**Issue by ailtisWSFR** [worldskills/worldskills-infrastructure-list#127]
Hi @fabian 
When a user makes a recommendation, it appears multiple times in the system as shown in the video linked below. 
https://www.dropbox.com/s/fpcmn2i80dvj0fz/Test%20bug1%20LI%20WSFR.avi?dl=0

**Comment by fabian** [comment]
@ailtisWSFR Ah yes sorry, this bug was introduced with some optimizations for the Recommendations page I did at the end of last year.

Can you confirm it's fixed now?

**Comment by ailtisWSFR** [comment]
@fabian Great, it does seem to have disappeared. 
Thanks for the fix!
