### ISSUE TITLE
globalization issues

### ISSUE THREAD

**Issue by PierreAnctil** [worldskills/worldskills-infrastructure-list#17]
Firstly there is no default language defined when the user accesses the application for the first time:

![image](https://user-images.githubusercontent.com/6544411/35089736-202fcd24-fc38-11e7-9d65-ebf8c04faf05.png)

We should default to the browser locale and then to en-US.

Secondly, when we select an incomplete language, there is no fallback language when the texts are not translated

![image](https://user-images.githubusercontent.com/6544411/35089839-59106978-fc38-11e7-87c3-23543cfd8631.png)

this second point is less important since it only implies that every available language has to be fully translated. So Portuguese should be disabled for now.

**Comment by gbervik** [comment]
Also can we change from `en_US` to `en` and `fr_FR` to `fr` so that they are not country specific?  For example, it would make sense for someone with a browser locale of `fr_BE` to get the French translation rather than the default.
