### ISSUE TITLE
Create infrastructure report

### ISSUE THREAD

**Issue by fabian** [worldskills/worldskills-infrastructure-list#24]
> Report to show infrastructure not confirmed filtered by priority / tier

**Comment by fabian** [comment]
In Skill overview list make it possible to filter status numbers by priority.

**Comment by PierreAnctil** [comment]
@fabian 
Can you please confirm the following statements?
- So this will be a **global** report 
- **Only** the not confirmed items will be displayed
- The **Secret** status is considered not confirmed
- Statuses will soon be possible to customize (#32), but the **basic statuses will always be here** (at least *confirmed*)
- **columns are the same** as the current requested items global export

Regarding the skill overview list I guess the filter will have to be added here:

![image](https://user-images.githubusercontent.com/6544411/39820004-12a2a1d0-53a5-11e8-9534-c6b3cbe86c11.png)

Should we also display it on the skill overview itself ?

![image](https://user-images.githubusercontent.com/6544411/39820174-816e85f2-53a5-11e8-828e-90ef229c2b46.png)

**Comment by fabian** [comment]
@PierreAnctil Sorry, the description of this task hasn't been very clear as it also took me some time to understand what's really needed. I'll try to answer your questions first and then describe how I think it should work.

---

> So this will be a global report

Well, "global" for each event.

> Only the not confirmed items will be displayed

No, we would also show confirmed items, to give an indication of the progress.

> The Secret status is considered not confirmed

Items with the status "Secret" should also be included.

> Statuses will soon be possible to customize (#32), but the basic statuses will always be here (at least confirmed)

This report should work with the dynamic statuses, showing a breakdown by status and then by tier.

> columns are the same as the current requested items global export

This should be an aggregated report, so not each single item should be listed.

> Regarding the skill overview list I guess the filter will have to be added here:

Yes, that seems like a good place for that.

---

So this is actually not a report about the priority on the supplied items, but a report of a new field that still needs to be added. So far we have called it "Tier" but I'm not sure if that's a good name as it's not really descriptive. "Urgency" might be a better name, but maybe there's an advantage in keeping it abstract so we can refine it for each event with a description.

A "Tier" defines until when the item should reach the status "Confirmed" so Experts see the Manufacturer and Model of the Supplied Item. Once they get that information, they can start preparing and train better for the Competition. For example:

- Tier 1: Manufacturer and Model need to be known 12 months before the Competition
- Tier 2: Manufacturer and Model need to be known 6 months before the Competition
- Tier 3: Manufacturer and Model need to be known 1 month before the Competition

Here's an example of how the report could look like:

| Skill | Tier 1 | Tier 2 |
| --- | --- | --- |
| Polymechanics and Automation | Requested: 3<br>Pending: 1<br>Confirmed: 1 | Requested: 9<br>Pending: 3<br>Confirmed: 4 |
| Information Network Cabling | Requested: 8<br>Pending: 4<br>Confirmed: 8 | Requested: 5<br>Pending: 3<br>Confirmed: 9 |

Not sure if Tiers should be columns or Statuses instead. Maybe there's also a nicer way to visualize this 2D data, can't think of one at the moment.

@gbervik Please check if this also matches your understanding.

**Comment by gbervik** [comment]
@fabian I think that works for an overview, but I think we need to be able to break it down by skill as well. If I saw that report and could see that there are unconfirmed items when approaching the deadline for that tier, I would want to know what those items were. Perhaps clicking on the skill name could show a detailed report for that skill.

Before we go too far with this one we should get sign-off from David and Jane. Lets show them an HTML mockup of what we think they want and get clarification from there.

**Comment by azanetti** [comment]
@fabian @gbervik as we are working actually on the specifications, designing the page will be part of the job. So, I let @PierreAnctil see with our team to make the mockup.

**Comment by PierreAnctil** [comment]
@fabian What do you think of this kind of display for the report ?

![image](https://user-images.githubusercontent.com/6544411/40226924-5c9a9740-5a8d-11e8-9126-94695fc3a57f.png)

It keeps things tight, makes you see very quickly the global amount of items for each status and you can spot the main issues easily.

Of course a caption will be displayed and the status matching the color will appear on hover.

Some charts could also be displayed on top of the report :
- Number of items per Status
- Number of items per Tier
- Number of items par Status and Tier (might be complicated depending on your answer to my next question)

What do you think will be the max number of statuses and tiers ?

**Comment by fabian** [comment]
@PierreAnctil Hmm, nice idea of using different font size, but I think it would quickly look messy and too hard to read with 50+ skills.

I think it's probably better to keep the existing progress bars (one for each tier):

![screenshot 2018-05-21 16 26 40](https://user-images.githubusercontent.com/13346/40312693-dc8b8dd2-5d13-11e8-85e7-d6277a8831c5.png)

Not sure if we need the additional charts - the total number of items per status is already visible on Skills overview page. Not sure if a total number of items in a tier is really helpful, but it could maybe be added in the column headings as informational text "Tier 1 (total 453 items)". The last thing would be covered by the table.

We would probably try to limit it to 3 tiers and 5 status.

**Comment by PierreAnctil** [comment]
@fabian 

> I think it's probably better to keep the existing progress bars (one for each tier):

I though of using the progress bar but the issue was that statuses will not be aligned between skills, so the reading is not as much accurate. We will provide both mockups so you can choose.

> Not sure if we need the additional charts - the total number of items per status is already visible on Skills overview page. 

I was speaking of inter-skills charts displaying the count per statuses / tiers globally for an event.
Using one progress bar per tiers as an example

**Tier 1**  ![image](https://user-images.githubusercontent.com/6544411/40344994-98e6c770-5d97-11e8-8f6f-83302f2a84ad.png)
**Tier 2**  ![image](https://user-images.githubusercontent.com/6544411/40344994-98e6c770-5d97-11e8-8f6f-83302f2a84ad.png)
**Tier 3**  ![image](https://user-images.githubusercontent.com/6544411/40344994-98e6c770-5d97-11e8-8f6f-83302f2a84ad.png)

That could be rather small and positioned on the right of the title, so no space is wasted.

Just tell me if this feature is useful

**Comment by fabian** [comment]
> I though of using the progress bar but the issue was that statuses will not be aligned between skills, so the reading is not as much accurate. We will provide both mockups so you can choose.

Perfect, thanks!

> That could be rather small and positioned on the right of the title, so no space is wasted.

Okay, yes maybe that could be useful and it doesn't take much.

**Comment by PierreAnctil** [comment]
@fabian We are starting the mockups on this point.

They should be ready before the end of the week.

**Comment by PierreAnctil** [comment]
@fabian here is the mockup: https://preview.axiocode.net/worldskills/skill-article-status-tiers.html

You will find a second version by scrolling down the mockup.

**Comment by fabian** [comment]
@PierreAnctil Thanks, I will forward and discuss the mockups internally.

Quick note: Each tier should also have a due date for reference purposes.

**Comment by fabian** [comment]
@PierreAnctil Quick question: In the first preview the status bubbles had different sizes depending on the number - did that not work at all or why did you leave it away now?

![image](https://user-images.githubusercontent.com/6544411/40226924-5c9a9740-5a8d-11e8-9126-94695fc3a57f.png)

![screenshot 2018-06-06 17 34 01](https://user-images.githubusercontent.com/13346/41048782-d0ac9044-69af-11e8-8f6c-36d324791e5a.png)

**Comment by PierreAnctil** [comment]
@fabian  You previously mentioned that the display would get messy with a changing font and 50 skills.

Do you want a version with changing bubble sizes ?

**Comment by fabian** [comment]
@PierreAnctil Yes, was just wondering if you ever tried it. No, it's fine, I can't really see it working well. Thanks! I've forwarded the mockups for internal feedback and should be able to get responses next week.

**Comment by fabian** [comment]
There hasn't been a lot of feedback, so I think we go with the known progress bars instead of the bubbles.

**Comment by fabian** [comment]
![screenshot 2018-08-15 14 35 46](https://user-images.githubusercontent.com/13346/44148408-9134d7da-a098-11e8-8e5f-4259dfe2bff4.png)
