### ISSUE TITLE
Non-workshop locations 

### ISSUE THREAD

**Issue by fabian** [worldskills/worldskills-infrastructure-list#26]
> Allow IL for Non-Workshop Locations
> - Meeting rooms, conference rooms etc
> - Sponsor booths

**Comment by PierreAnctil** [comment]
@fabian can please you add more details about what should be done. The only locations I see is the one on the supplied item
 
![image](https://user-images.githubusercontent.com/6544411/39824891-c0367f14-53b0-11e8-9a62-db7978da0945.png)

Do you just want more locations to be available here? (seems to simple too be accurate)

**Comment by fabian** [comment]
@PierreAnctil A the moment The idea each "Infrastructure List" is linked to a Skill. The idea here was to make it possible to have an "Infrastructure List" that is not linked to a Skill and simply has a description instead.

So that the Competition Organizer could create a new "Infrastructure List" with the name "Conference Hall A" for example. No workshop manager or expert would have access to that list, it would only be used by the Competition Organizer itself.

**Comment by WorldSkillsFrance** [comment]
@fabian is right and it's also to WSI to take care of it @PierreAnctil 

Fabian, When do you think this issue could be online? not urgent to us, but it could be good to have it around July or August

**Comment by PierreAnctil** [comment]
So what should basically be needed:
- a new form for creating and editing Lists with the following properties
  - Name
  - *Number*? --> skills are sorted by number so maybe this is needed?
  - Description (HTML)
- A new button *Add List* on the home page that triggers the appearance of the new list form in a side panel
- edit and remove button on the non-workshop lists
- clicking on the list name displays what is currently known as the *skill view* and should now be called the *list view*
  - Display is exactly the same except 
    - the label "Skill management" which should be renamed "List management"
    - the "Requested items for skill" button which should be renamed "Requested items for list"

**Comment by fabian** [comment]
- I think we should sort the lists alphabetically, that way we also don't need the number for those lists.
- I don't think a description is required for the list.
- Correct, I think we can change the labels globally from "Skill management" to "People", and "Requested items for skill" to "Requested Items".
