### ISSUE TITLE
Open catalog by URL keeps loading

### ISSUE THREAD

**Issue by PierreAnctil** [worldskills/worldskills-infrastructure-list#3]
When you open the catalog by using direct URL, the page loads infinitely

![2017-12-07_09-03-59](https://user-images.githubusercontent.com/6544411/33704756-f71e143e-db2d-11e7-8d74-d90eab22da82.gif)

**Comment by PierreAnctil** [comment]
NB when one refreshes the catalog (F5) that seems to be working but the headers translations are lost

![image](https://user-images.githubusercontent.com/6544411/37586729-926c00ac-2b5d-11e8-84db-32b24a693d6c.png)

**Comment by WorldSkillsFrance** [comment]
@fabian could you take care of this ?

**Comment by WorldSkillsFrance** [comment]
@fabian if you fixed bug could you close this issue ?

**Comment by WorldSkillsFrance** [comment]
but seems not fixed : 
![image](https://user-images.githubusercontent.com/33081412/39426401-f11ea60c-4c7f-11e8-97b3-6ec688f6c20f.png)

**Comment by Joni-Aaltonen** [comment]
closed and PR created
