### ISSUE TITLE
Escaped message

### ISSUE THREAD

**Issue by PierreAnctil** [worldskills/worldskills-infrastructure-list#33]
![image](https://user-images.githubusercontent.com/6544411/35905513-b99008c6-0be7-11e8-9619-75fcdfce3dfe.png)

**Comment by WorldSkillsFrance** [comment]
Hello everyone, Does this is fixed ?

**Comment by WorldSkillsFrance** [comment]
@PierreAnctil  Did you fixe that ?

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance No I didn't because this is not related to our developments and we have no support contract.

**Comment by Joni-Aaltonen** [comment]
fixed in bcf8c3b

**Comment by WorldSkillsFrance** [comment]
Hi @Joni-Aaltonen 
when do you push to production all modifications that you do ?

**Comment by Joni-Aaltonen** [comment]
Hi @WorldSkillsFrance 
I'm creating pull requests for @fabian who will handle deployments
