### ISSUE TITLE
Catalog mass edit tool

### ISSUE THREAD

**Issue by PierreAnctil** [worldskills/worldskills-infrastructure-list#38]
Allow supplied item mass editing.

## UI changes:

![image](https://user-images.githubusercontent.com/6544411/36583250-2ae29b4e-1875-11e8-8888-8233748da10a.png)

"Edit selected item" → "Edit selected item(s)"

![image](https://user-images.githubusercontent.com/6544411/36583445-13c795c6-1876-11e8-956c-5db4ebe557c2.png)

"Editing item" → "Editing item(s)"
"Save Item" → "Save Item(s)"

## Behavior changes:

When only 1 item is selected nothing changes.

When several items are selected
- Shared values are displayed
- When values are different among items a placeholder "multiple values detected"

On form submit all and only changed values are updated on the selected items

**Comment by fabian** [comment]
This sounds okay to me.

Would the field then be empty if multiple values are detected for that field? There's an edge case here if someone wants to clear the value in all those items with different values, but it's probably unlikely enough to not implement it.

**Comment by WorldSkillsFrance** [comment]
Hi @Joni-Aaltonen / @fabian 
I find bugs on supplie item

- "inline editing" I made a video to show you. 
https://www.dropbox.com/s/4kqochnazn6nh0t/Bug%20Supplie%20item%20inline%20editing.mp4?dl=0 

- "mass edit tool" I made a video to show you. 
https://www.dropbox.com/s/t55et4mzr028zf2/Bug%20catalogue%20mass%20editing%20tools.mp4?dl=0

After editing we have the come back of display bug : 

![image](https://user-images.githubusercontent.com/33081412/40060322-9ec9239a-5856-11e8-8f5c-a49abce4285e.png)
