### ISSUE TITLE
Standard sets access by URL fail

### ISSUE THREAD

**Issue by PierreAnctil** [worldskills/worldskills-infrastructure-list#4]
![2017-12-21_09-29-36](https://user-images.githubusercontent.com/6544411/34247080-8f365908-e631-11e7-9349-3fd922961cd8.gif)

**Comment by WorldSkillsFrance** [comment]
@fabian if I well remember with that we mask this option of "Standard sets". and will take care later. It seems to me that you made this change so may be we could close this issue

**Comment by fabian** [comment]
Yes, not relevant anymore 👍
