### ISSUE TITLE
People-permission

### ISSUE THREAD

**Issue by WorldSkillsFrance** [worldskills/worldskills-infrastructure-list#41]
Hello, Fabian and Adam,

I hope you are well and have had a great weekend

**BUG 1**
i try to give permission to expert and organizer team but i can't find roles.
![image](https://user-images.githubusercontent.com/33081412/36664697-c3cef07e-1ae5-11e8-9d96-bf591442e834.png)
Arthur ILTIS, could see roles you add but not me.
**BUG 2**
We Also try do a position on Davy Rezeau and when we selected "WorldSkills France Nationals 2018"  and when we click on add, it does not work. Could you have a look ?
**BUG 3**
When Arthur ILTIS add permission on Davy REZEAU on french event it works (screen of is laptop)
![image](https://user-images.githubusercontent.com/33081412/36665045-c21a50f6-1ae6-11e8-9931-b45210ff6e78.png)
But not on my screen :
![image](https://user-images.githubusercontent.com/33081412/36665067-d3c2cf4a-1ae6-11e8-967d-68c528b792e6.png)

It would be fantastic if you could solve this bug today.

**Comment by gbervik** [comment]
It was a permissions problem. I've given you the correct permission now, so it should work for you.
