### ISSUE TITLE
On Skill Print View page, the link "Back to worldskills.org" is wrong

### ISSUE THREAD

**Issue by azanetti** [worldskills/worldskills-infrastructure-list#42]
The link "Back to worldskills.org" is wrong and redirects to "https://www.worldskills.org/internal/".
It should redirect back to the previous page instead and handle correctly the environment (dev, staging or prod).

![capture d ecran 2018-02-26 a 16 05 47](https://user-images.githubusercontent.com/546856/36677650-05adeb52-1b0f-11e8-880a-9b07833536ff.png)

**Comment by fabian** [comment]
This view is opened in a new tab from worldskills.org, so going back in history wouldn't always work. I've removed the link instead now.
