### ISSUE TITLE
WSFR Permission People - update

### ISSUE THREAD

**Issue by WorldSkillsFrance** [worldskills/worldskills-infrastructure-list#48]
@gbervik  Could you update the permissions on the different French profiles with the following document:
[FR_IL_permissions_matrix.xlsx](https://github.com/worldskills/worldskills-infrastructure-list/files/1838120/FR_IL_permissions_matrix.xlsx)
You will find in yellow the changes that have been made to the first file.
(Remove permissions for sector manager)

Could you tell me when you made these updates and if it concerns staging and / or production environment.
Thanks a lot

**Comment by gbervik** [comment]
I've removed the `EditItemStatus` permission from Sector Manager profile on staging and production, which leaves the following permissions:

`View`
`Recommend`
`Workshop Manager`
`Sector Manager`

@fabian since we don't have an `EditSuppliedItems` permission at the moment, does that mean that I should remove the `Sector Manager` permission?

**Comment by fabian** [comment]
@gbervik Yes, in fact both `Sector Manager` and `Workshop Manager` should be removed for now.

**Comment by gbervik** [comment]
Ok, I've removed `Sector Manager` and `Workshop Manager`. The sector managers only have `View` and `Recommend`

**Comment by WorldSkillsFrance** [comment]
Does sector manager have permissions to do an extraction of IL
Adama, can you tell me what does have expert please ?

**Comment by gbervik** [comment]
Expert currently only has permissions for `View` and `Recommend`, the same as Sector Manager. I think that means they don't have permission to do an extract, is that correct @fabian ?

**Comment by fabian** [comment]
Correct, `View` and `Recommend` currently only gives them access to the "public view", e.g. https://il.worldskills.org/#/event/316/skill/489/public

**Comment by WorldSkillsFrance** [comment]
Ok, does it possible taht sector manager can have access on requested item extraction ?

**Comment by fabian** [comment]
No sorry, there's no separate permission for accessing the requested items export separately at the moment. We would have to give them access for editing as well. But they can always have a look at the requested items in the public view.

**Comment by WorldSkillsFrance** [comment]
Yes ok, the idea was that they was able to extract the needs of several skills to find partners.
I would be creat if you could make it possible but is not that urgent

**Comment by WorldSkillsFrance** [comment]
Hi @gbervik  @fabian,
I think this issue can be close
