### ISSUE TITLE
Open to Expert/WSS/Sector manager edition to Requeste item for a period of time

### ISSUE THREAD

**Issue by WorldSkillsFrance** [worldskills/worldskills-infrastructure-list#49]
Due to the addition of the "ask for a modification" expert, WSS and sector manager can not make any direct changes in the requeste item part and can only make "ask for a modification".

The idea would still be able to give access to the following features for a period of time:
- Edit requested items
- Edit item status
This function would be used for example when CPW when working in a group in front of the same PC and may be on week after.

@fabian could you make sure that we can have this before our CPW  which will take place from April 23 to 28. 
The best would be that the lists be open for the different actors from april 32 to may 8

**Comment by PierreAnctil** [comment]
seems like a duplicate to https://github.com/worldskills/worldskills-infrastructure-list/issues/39

**Comment by fabian** [comment]
Ha! I thought we already have this issue, just couldn't find it - thanks Pierre! 😄 Will try to combine the issues next week.
