### ISSUE TITLE
Move Unit of item to Requested item

### ISSUE THREAD

**Issue by WorldSkillsFrance** [worldskills/worldskills-infrastructure-list#50]
Hi Fabian,
As mentioned previously, could you move the record of the "unit" of an item in Requeste item instead of Supplied item ?

Could you make sure that we can have this before our CPW which will take place from April 23 to 28.

**Comment by WorldSkillsFrance** [comment]
Fabian could you add this unité please : 
- Unités
- Boite
- Bottes
- Bouteilles
- Feuilles
- Kit
- Mètre linéaire
- Mètre carré
- Mètre cube

**Comment by fabian** [comment]
@WorldSkillsFrance Can you also provide the English translations?

**Comment by WorldSkillsFrance** [comment]
Units>Unités
Box>Boite
Boots>Bottes
Bottles>Bouteilles
Leaves>Feuilles
Kit>Kit
Linear meter>Mètre linéaire
Square meter>Mètre carré
Cubic meter>Mètre cube

**Comment by fabian** [comment]
@WorldSkillsFrance Okay, I've added them on staging now. I haven't added "Units" as having the Unit "Units" doesn't make sense to me - I would rather leave it empty then. We already have "Pieces" which is maybe what you are looking for?

**Comment by WorldSkillsFrance** [comment]
Ok it's a bit different but ok no problem. 
Thx
