### ISSUE TITLE
Event overview page: skill names don't refresh when switching language

### ISSUE THREAD

**Issue by azanetti** [worldskills/worldskills-infrastructure-list#51]
Skill names don't change when switching language from the selector at the bottom of the page.

**Comment by PierreAnctil** [comment]
Globally the data are not reloaded when changing language.

Refreshing the page might be the easiest way, but some pages might not support refresh (assuming all pages support refresh).

**Comment by WorldSkillsFrance** [comment]
@fabian i just saw that you add WSI to take care about this bug could you tell us when this bug is fixed please

**Comment by Joni-Aaltonen** [comment]
added translation change listener to main.js (049ab90) which fix reloads the view, a bit more testing needed in subviews before merge
