### ISSUE TITLE
Redirect user with read only/recommend permission to public view

### ISSUE THREAD

**Issue by fabian** [worldskills/worldskills-infrastructure-list#58]
At the moment if a read only user tries to access https://il.worldskills.org he only gets an error message and cannot proceed further:

![screenshot 2018-04-12 15 16 06](https://user-images.githubusercontent.com/13346/38680000-812ee528-3e65-11e8-80f0-c2548485a47a.png)

It would be good if the user automatically get redirected to a public of a skill he has access to:

![screenshot 2018-04-12 15 17 02](https://user-images.githubusercontent.com/13346/38680230-10b2a982-3e66-11e8-8074-aa8c9e3bba52.png)

Ping @WorldSkillsFrance as discussed in our call.

**Comment by PierreAnctil** [comment]
Since one can access skills public view, one need to be able to list accessible skills.
So in my opinion the list of skills should be turned public and only display accessible elements.
The click on a skill should of course redirect to the skill's public view.

**Comment by fabian** [comment]
Yes, that works for me too.

**Comment by WorldSkillsFrance** [comment]
Hi @fabian 
I guess this issue can be closed.
I put a reminder for May 14 in order to close the permissions of WSS and E. 
We will see together how to do at that moment.
Regards

**Comment by fabian** [comment]
I leave this issue open, as we still should implement a list of skills for read-only users.

**Comment by fabian** [comment]
- Change `VIEW` to entity based
- Adjust permission checks
- List all Skills with IL where user has `VIEW` permission 
- Link to IL

**Comment by Joni-Aaltonen** [comment]
closing this, please reopen if bugs appear

**Comment by fabian** [comment]
Will be deployed to production next week.
