### ISSUE TITLE
Approval process

### ISSUE THREAD

**Issue by PierreAnctil** [worldskills/worldskills-infrastructure-list#6]
- A recommendation level permission 
- User interface to be on public view
- Allow multiple recommendations
- Provide reason for rejection of recommendation
- Recommended items are not shown in IL public view
- Can recommend new item, remove item, change item
- Does not create an item in the catalogue until the recommended item is approved and becomes a requested item
- Recommendation fields: 
  - description
  - quantity
  - potential supplier
  - wrong supplied item checkbox
  - comment, and images
- Cannot make recommendations on items that are green (confirmed)

**Comment by PierreAnctil** [comment]
@worldskills/geeks @WorldSkillsFrance  
What does "wrong supplied item checkbox" represents in the recommandation fields ?

I guess comment and images are new data attached to the recommandation as a context ?

**Comment by fabian** [comment]
@PierreAnctil The idea with "wrong supplied item checkbox" was that if a requested item has been approved and linked to a supplied item, the user can flag that the supplied item does not match to what was requested.

Comment would be part of the recommendation and images would be attached.

**Comment by PierreAnctil** [comment]
Thanks @fabian 

Now lets validate the requested item update workflow.

There are 2 sources of update:
- recommandations (possibly multiple a the same time)
- direct edition

To keep it simple, I suggest that 
- each validated recommandation updates the requested item 
- when an item is updated pending recommandations are kept
- a recommandation shows a diff between the **current** requested item (and not the one at the time of the recommandation) on the recommended columns

**Comment by fabian** [comment]
@PierreAnctil Yes, the proposed workflow makes sense to me.

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance @worldskills/geeks Here are some mockups  of the UI.

Recommandation: https://preview.axiocode.net/worldskills/print-view.html
Validation: https://preview.axiocode.net/worldskills/validation-view.html
Recommandations display in the skill view: https://preview.axiocode.net/worldskills/general-view.html

**Comment by PierreAnctil** [comment]
cc @JonathanVanRaemdonck

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance @worldskills/geeks 
Are the mockups OK or does anything need to be changed?
We will be starting the UI dev very soon so we need to know as soon as possible 🙏

**Comment by fabian** [comment]
@PierreAnctil The proposal looks good! I think we should make this feature optional per event, so we can enable or disable it if needed.

**Recommandation**
- I think the edit and delete button are not totally clear. How about having one "Suggest edit" button instead and then having a "Suggest deletion" button in the modal?

**Validation**
- I think the recommendation requests would be handled by the Workshop Manager, so it would probably make sense to integrate it as a tab into the Skill view?
- Showing both the before and after is good, but I would maybe show the before on the left and the after on the right side instead of under each other.
- "Wrong supplied item" would span both rows (same as comment and images).

**Recommandations display in the skill view**
- To keep the layout consistent I would show the icon after the item name (as there will also be items without any recommendations).
- I think it would be helpful to link to the Validation view where the recommendation can be accepted or declined, or would that be possible in this view as well?

**Comment by PierreAnctil** [comment]
> I think the edit and delete button are not totally clear. How about having one "Suggest edit" button instead and then having a "Suggest deletion" button in the modal?

I'm not sure one wanting to remove an item will want to click on "Suggest edit".  Naming the column "Suggestions" and having a tooltip on each button might be better don't you think so ?

> I think the recommendation requests would be handled by the Workshop Manager, so it would probably make sense to integrate it as a tab into the Skill view?

That would surely be handy. That may be done in a second time I guess ? We are short on the schedule here 😉 

> Showing both the before and after is good, but I would maybe show the before on the left and the after on the right side instead of under each other.

What do you think about that @WorldSkillsFrance  ?

> Wrong supplied item" would span both rows (same as comment and images).

👍 

> To keep the layout consistent I would show the icon after the item name (as there will also be items without any recommendations).

👍 

> I think it would be helpful to link to the Validation view where the recommendation can be accepted or declined, or would that be possible in this view as well?

👍 
I suggest to add it under the caption area 

![chrome_2018-02-23_09-34-34](https://user-images.githubusercontent.com/6544411/36585121-d67b1dee-187c-11e8-9283-4027f9f0639a.png)

**Comment by PierreAnctil** [comment]
Small change:
The caption icons should be changed.
- addition --> (➕) 
- edition --> (🖊) 
- removal --> (➖)
The color should be gray for all icons.

**Comment by PierreAnctil** [comment]
NB : Since one should be able to suggest on a category where no items are present yet, people with RECOMMEND permission should see empty categories (to have access to the 
![image](https://user-images.githubusercontent.com/6544411/36841418-8b509878-1d48-11e8-9c46-1d717831bd2b.png) button)

**Comment by WorldSkillsFrance** [comment]
> Small change:
> The caption icons should be changed.
> 
> addition --> (➕)
> edition --> (🖊)
> removal --> (➖)
> The color should be gray for all icons.

Ok works for me, maybe put in a cercle or a square like the WSI edit buttons would be perfect.

**Comment by WorldSkillsFrance** [comment]
@PierreAnctil 

- When experts and WorkShop supervirsor ask for and item which is not on the catalogue can you make sure that in the forme they will have to choose a "Sub categorie"

-  Can you also make sure as discuss in our last zoom meeting that, when someone want to add a line they could add in the righ catégorie they want .
For exemple in the picture below you could add only a item in two catégori.
![image](https://user-images.githubusercontent.com/33081412/38242103-394db56e-3734-11e8-92f5-e83a4dd74d35.png)

@gbervik @fabian, can you confirme that you are ok with that

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance as stated by @fabian suggesting the item subcategory will not be possible since it is related to the supplied item.

Regarding the skills categories this is already how we have been implementing the feature. But thanks for writing it down in the issue 👍

**Comment by azanetti** [comment]
Hello @WorldSkillsFrance, estimate time for the addition is 4h of work. Is it OK for you?

**Comment by WorldSkillsFrance** [comment]
Hello @azanetti 
I guess yes, you said to me by phone fews days ago, that you can take care of a small modification

**Comment by WorldSkillsFrance** [comment]
@fabian as discuss in our meeting could you have a look to do it please. Thx

**Comment by Joni-Aaltonen** [comment]
Fields added and pull request created, closing for now.
Feel free to reopen in case of bugs or changes.

**Comment by WorldSkillsFrance** [comment]
Thx @Joni-Aaltonen, could you just tel us when this will be push in production that we can inform our team please.

**Comment by fabian** [comment]
@WorldSkillsFrance I will deploy it to production next week together with all the other things.
