### ISSUE TITLE
Display Management of skills and public view

### ISSUE THREAD

**Issue by WorldSkillsFrance** [worldskills/worldskills-infrastructure-list#64]
Hi all 
![image](https://user-images.githubusercontent.com/33081412/38937104-b13d7f6a-4322-11e8-842f-550b7d55ed50.png)
AND
![image](https://user-images.githubusercontent.com/33081412/38937129-c0e73758-4322-11e8-9cc4-1711018e63f5.png)

Could you had on both view (skills and public view)  columns with the following information :
- Unit (after quantity)
- Potential supplier (after item)
- Model (should also be in requeste item; if not at least user should be able to add remarques) !!! This is important for our CPW.

**Comment by azanetti** [comment]
@PierreAnctil could you estimate the time needed to add them on both views? Or maybe @fabian will take over it?
@WorldSkillsFrance if we need do it, it is a change request from what has been validated on issue #6 (see mockups in comments), do you agree to be billed separately for that?

**Comment by gbervik** [comment]
@WorldSkillsFrance we spoke about this yesterday, and Fabian may have time to address this. We spoke about having an expanding view for the extra information.

**Comment by WorldSkillsFrance** [comment]
This is not about approval process, but this is about add WSI IL to WSFR as righ in our first estimate.
I can not accept any further quote, because I have no more budget. 
Moreover in this case has already been estimate in the first quote.
In order to free up time to Axiocode and to be sure that you have finished the approval process. I asked Adam and Fabian to take care of it.
It only remains for me to hope that Fabian has the time to do it before our CPW

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance does the scope of this issue include

- moving the Model from the supplied item to the item requested ?
- making these new fields subject to recommendations (as discussed earlier) ?

@worldskills/geeks I guess the expanding view should be close to what we have in the [recommendation interface](https://staging-il.worldskills.org/#/event/438/recommendations)?

**Comment by WorldSkillsFrance** [comment]
@fabian 
Could you add here : ?
![image](https://user-images.githubusercontent.com/33081412/39421080-b4aab3e0-4c67-11e8-81c0-560933f29207.png)
1- Unit
2- Potential supplier

**Comment by WorldSkillsFrance** [comment]
@fabian did you get my previous message ?

**Comment by fabian** [comment]
The "Print view" actually already had units, I've added the Potential Supplier now.

I've also added units to the "Skill view" now. Unfortunately the space is rather limited, so I can't add the Potential Supplier there. You can always get the Potential Supplier by editing the row.

On staging now, looking at deployment to production later this week or next week.
