### ISSUE TITLE
Split existing Supplied Item when creating a new Requested Item

### ISSUE THREAD

**Issue by fabian** [worldskills/worldskills-infrastructure-list#67]
When creating a new Requested Item, an existing Supplied Item can be used or a new one can be created. It would be helpful to have an option to "split"/"fork" and existing Supplied Item: create a copy of it and link it to the Requested Item.

**Comment by Joni-Aaltonen** [comment]
@WorldSkillsFrance there are a couple of changed/new translations that need updates in french, mainly in the "add requested item" form 

```"CHANGE_TO_ANOTHER_ITEM_HELP": "In order to create a new item with this description, hit enter<br><br><b>OR</b> if you'd like to search for another item, keep typing",```

```"ITEM_DOESNT_MATCH": "If this doesn't match your needs, please use one of the options below.",```

```"ITEM_ALREADY_CREATED": "This is an item already created by the organizer, or an item already used in another skill.",```

```"SPLIT_SUPPLIED_ITEM": "Create a new copy of Supplied Item",```

```"DONT_SPLIT_SUPPLIED_ITEM": "Creating a copy when saved, click to cancel",```

```"ITEM_SPLIT_DESCRIPTION": "<b>OR</b> create a new copy of the item to be used in this skill",```

```"CLONE_ITEM_HELP": "Creating a new copy of the supplied item, please select the subcategory for the item",```

```"CHANGE_TO_ANOTHER_ITEM_HELP": "In order to create a new item with this description, hit enter<br><br><b>OR</b> if you'd like to search for another item, keep typing",```

**Comment by WorldSkillsFrance** [comment]
@ailtisWSFR could you take care of it thx
