### ISSUE TITLE
BUG event/IL

### ISSUE THREAD

**Issue by WorldSkillsFrance** [worldskills/worldskills-infrastructure-list#69]
Hi all,

I get a news bug today that when i work on IL, I get back sometime on the following page :  
![image](https://user-images.githubusercontent.com/33081412/39394333-595bd344-4ad1-11e8-8259-3011c6fc67a8.png)
To get back on skills i have to clic on the header.

**Comment by Joni-Aaltonen** [comment]
Hi @WorldSkillsFrance - this is meant to show a selection of roles where the user can select which "role" they want to use the application as, for example if an expert has multiple skills, they would use this to select the skill they want to edit.

However I've changed this logic in a pull-request last week, which @fabian will be pushing out to production sometime soon. 

From now on the application will automatically select the first applicable role, and show a role switcher on the top-right corner of the navigation header and the role can be switched from there.
