### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by PierreAnctil** [worldskills/worldskills-infrastructure-list#7]
- Add sub category
- Add user interface for managing categories
- Set tier/priority level of each item

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance can you explain what 

> Set tier/priority level of each item

implies ?

Should we add a new field in the catalog items ?

**Comment by WorldSkillsFrance** [comment]
Hi
Priority will have to be for each item and will be registered / modified in the catalog

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance said that the values should probably be a list of static texts like

- Very important
- Important
- Less important
- Not important

The reason is using just an integer would be confusing since users might not know if 1 is the highest or the lowest value.

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance can you provide us with the list of values to be used?

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance to answer your question all the people having the specific permission **EditItemCategories** can manage item categories and subcategories.

**Comment by WorldSkillsFrance** [comment]
> @WorldSkillsFrance can you provide us with the list of values to be used?

We don't for ce moment the value in our catalogue. So leave it like that
