### ISSUE TITLE
Catalogue Mass editing tool

### ISSUE THREAD

**Issue by WorldSkillsFrance** [worldskills/worldskills-infrastructure-list#71]
It would be nice to be able to edit several lines in one go.
For example, when we have to add the name of a partner who could supply the material

![image](https://user-images.githubusercontent.com/33081412/39426496-637f0598-4c80-11e8-808a-29de13c00d8f.png)

**Comment by PierreAnctil** [comment]
That's exactly what is described in https://github.com/worldskills/worldskills-infrastructure-list/issues/38
I close this one.
