### ISSUE TITLE
1 expert 2 skills

### ISSUE THREAD

**Issue by WorldSkillsFrance** [worldskills/worldskills-infrastructure-list#73]
Hi Fabian,
In some case i would like to connect 1 expert to 2 IL skills.
I check with Adam, the process and it look like i do the right thinks.
Could you have a look on the code if everything is good ?
Thx 
Simon

**Comment by WorldSkillsFrance** [comment]
@fabian did you have time to have a look on this ?
Two of my expert can't work on IL and i would like to give them a solution about you to work on it

**Comment by fabian** [comment]
@WorldSkillsFrance Okay, I will try to have a look at this today too.

**Comment by Joni-Aaltonen** [comment]
Hi @WorldSkillsFrance - You are already able to achieve this by adding multiple expert positions to the person

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/428709/39756005-875ff12e-52d0-11e8-82ad-30ffabf858b7.png">

You'll also need to make sure that the person has the correct permission in people of course
<img width="961" alt="image" src="https://user-images.githubusercontent.com/428709/39756021-9bd88cc4-52d0-11e8-852a-39c07e13a3fb.png">

once the expert logs in to the IL, they should get a selection of the role they want to use

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/428709/39756040-b0fd9fae-52d0-11e8-9921-bc73b70f7740.png">


this can also be switched using the switch role functionality on the top of the navigation
<img width="785" alt="image" src="https://user-images.githubusercontent.com/428709/39756058-bf3986e6-52d0-11e8-8a0e-7274594aa2e2.png">

**Comment by WorldSkillsFrance** [comment]
Hi @Joni-Aaltonen ,
You right and i did the good precedure as show to Adam.
I guess Fabian fix some thing because my expert say that it works now.

Remind just one thing : When my expert connects now he has your last screenshot but it is to mark "Workshop manager" and not "Expert"

**Comment by Joni-Aaltonen** [comment]
@WorldSkillsFrance that's right - the use role is called WorkShop Manager internally, experts are given a role of WorkShop Manager. This can be a bit confusing, but it's because of WSI specific reasons.

**Comment by WorldSkillsFrance** [comment]
Hi @Joni-Aaltonen,
It seems not working well. Our expert in cabinetmaking have access on is skills and joinery so this is good but our expert in joinery have access only on cabinetmaking and not is skills.
It would be wonderfull if you could look and fix this today.
Thx

**Comment by Joni-Aaltonen** [comment]
@fabian could you please take a look at this as I don't have access to prod/puppeteer

**Comment by fabian** [comment]
Sorry, can't have a look at it today, about to head out, will check on Monday.

**Comment by WorldSkillsFrance** [comment]
Loïc ROYER

**Comment by fabian** [comment]
@WorldSkillsFrance Okay, I was now able to manually fix the issue for Loïc ROYER.

I also found an issue in the application which caused the problem, will look into that.
