### ISSUE TITLE
Bug Upload file in request item

### ISSUE THREAD

**Issue by Simon-Woirgard** [worldskills/worldskills-infrastructure-list#78]
Hi @fabian 

You will be able to see in the video the bug when we want to import a file into a skill. (in french but not importe because you have pictures)
Could you correct that when you have a minute please

https://www.dropbox.com/s/jx7md5i7fo0qgum/Bug%20import%20files.mp4?dl=0

**Comment by fabian** [comment]
@Simon-Woirgard @ailtisWSFR Does this issue still exist?

**Comment by ailtisWSFR** [comment]
@fabian I can't see anymore the video made by Simon but I've tried and do still notice issues about it : 

 - No problem with uploading files (I've tried with .jpg and .pdf)
 - Bug 1: A "Not found" message when I try to delete a file
 - Bug 2: impossible to view the file (on the public view): When I click on it, I'm redirected to a web page with the message: "No direct access" (URL of the page: https://il.worldskillsusercontent.org/ )

**Comment by fabian** [comment]
Okay, @Joni-Aaltonen can you have a look at those issues when you get a chance?

**Comment by Joni-Aaltonen** [comment]
@ailtisWSFR It seems that this bug was introduced with code changes by Axiocode regarding file uploads. I've now fixed the code for both the API and the Client, Fabian will be reviewing and deploying the changes sometime soon.
