### ISSUE TITLE
Mass edit tool

### ISSUE THREAD

**Issue by PierreAnctil** [worldskills/worldskills-infrastructure-list#8]
Allow infrastructure lines (requested items) to be globally searched and mass edited

**Comment by PierreAnctil** [comment]
@worldskills/geeks @WorldSkillsFrance 
It has been agreed with @WorldSkillsFrance that the following fields would be mass editable:
- Status
- supplier
- price
- Energy (Volts, etc.)
- Category

However, the energy data is related to a supplied item (catalog) and not to a requested item. That may be because @WorldSkillsFrance wanted this field to be on requested item. 

So what should we do? 
- make those fields not mass editable?
- keep those fields mass editable and update the supplied item?

**Comment by PierreAnctil** [comment]
@worldskills/geeks @WorldSkillsFrance  I still need an answer on the above question.

Can you also state if the "supplier" field is the potential supplier or the supplier on the supplied item (In which case the previous question has to be answered again).

**Comment by fabian** [comment]
I think it's dangerous to update the supplied item in a mass edit action as that's not transparent to the user. I think we should make the energy data not mass editable in the requested items view.

If multiple requested item would get the exact same energy data, they should maybe be linked to the same supplied item.

If multiple supplied item should get the exact same energy data we should probably think about a mass editing for supplied items.

**Comment by WorldSkillsFrance** [comment]
Hi all, agree with Fabian about the modification of the energy information.
Regarding supplier please reporte to the issue #5 comment

**Comment by WorldSkillsFrance** [comment]
@fabian Could you close this issue 
To avoid confusion about mass editing tool i create 2 news issue:
1- #70 for the request item who axiocode have to take care of it
2- #71 for the supplied item
