### ISSUE TITLE
Permission Bug

### ISSUE THREAD

**Issue by Simon-Woirgard** [worldskills/worldskills-infrastructure-list#81]
Hi all,
We just find a new "bug" in the IL. All IL manager with the permission "FR-Admin" does not have the same access. 
For exemple
Angelique HADDAD does not have access  "Skill Participants Override"
![image](https://user-images.githubusercontent.com/33081412/40061805-0b8714f8-585a-11e8-8b93-af439fec84f8.png)
And Arthur ILTIS does not have access on "Item categories and subcategories" 
![image](https://user-images.githubusercontent.com/33081412/40061900-40f9dc2e-585a-11e8-9272-c5524b724b7c.png)
Could you tell me if it's normal and how we could fix that ?
Thanks

**Comment by fabian** [comment]
@WorldSkillsFrance I've added the role EditConfig now to the permission profile "FR - Admin", that should give access to "Skill Participants Override".

Arthur only has the permission profile "FR - Organizer" - you can fix his permissions by giving him "FR - Admin".

**Comment by WorldSkillsFrance** [comment]
Yes ok thx
