### ISSUE TITLE
Number of status for French national finals

### ISSUE THREAD

**Issue by ailtisWSFR** [worldskills/worldskills-infrastructure-list#82]
Hi Fabian,

Regarding the number and detail of statuses needed for our National Finales : 
We will need 4 status : 
 – Green: Confirmed / Confirmé (FR)
 – Yellow: Pending / En cours (FR)
 – Orange: Prospect / Prospect (FR)
 – Red: Requested / A rechercher (FR)

On the “Print view” : 
-	All the 4 status allow viewing the “Details” of the item
-	“Actions” are allowed for statuses “Requested”, “Prospect” and “Pending” and not if the status is “Confirmed”. 

We do not need the “Secret” status. 

Thanks

**Comment by fabian** [comment]
Ready for deployment next week.
