### ISSUE TITLE
Change of "Potential supplier" when we change status of request item ! 

### ISSUE THREAD

**Issue by ailtisWSFR** [worldskills/worldskills-infrastructure-list#94]
Hi,
Here is a huge bug that I notice today when using the IL : 
When I change the status of a request item, the potential supplier sometime change when I haven't touch it! 
It's a big problem for us that can potentially put a huge mess in our IL (and already have since I've spent the day working on the status of request items)! 
See below a video of the bug : 

https://www.dropbox.com/s/fddsut7vq656u0g/Status%20Bug.mp4?dl=0

Thank to solve this as quick as possible.

**Comment by fabian** [comment]
@ailtisWSFR The problem existed if you edited the Potential supplier of one item and then save changes on another item without a Potential supplier. A temporary variable wasn't reset properly and led to this behaviour.

I've pushed a fix to production now.

**Comment by ailtisWSFR** [comment]
@fabian Thanks. It did also exist if I save changes on another item with a Potential supplier (the Potential supplier was then replaced by the last one that I have edited).  Is this fixed as well?

**Comment by fabian** [comment]
Yes, that is fixed as well.
